### PR TITLE
Added Unit test, folder structure, naming #25 #22

### LINKED ISSUE #22: [Feature] Verander naam van het project

### LINKED ISSUE #25: [Feature] Voeg unit test project toe
**Beschrijving**
Er moet een unit test project worden toegevoegd aan de solution

**Reden**
Om valideren of geschreven code doet wat we willen.

**User Story**
N.v.t

**Criteria / Definition of Done**
Als we kunnen unit testen doormiddel van het project

**Risico**
Laag

**MoSCoW-prioriteit**
Must-have

**Geschatte tijdsduur**
30 min

### PR DESCRIPTION
**Pull request by rodeknopje**
Added a xUnit project to write unit tests in.
There are now 2 projects in the solution Dartin.Application and Dartin.UnitTests
image

Unit test can be written like this, functionality and models from the Application can be used in the tests.
image

To find more info about writing xunit test. 
https://xunit.net/docs/getting-started/netcore/visual-studio

### CODE REVIEW

**Review by Hoekstraa — APPROVED** [review]
Helemaal bole.

**Comment by tr4wzified** [comment]
Goedgekeurd

**Review by tr4wzified — APPROVED** [review]
Goede / logische rename van bestanden, logische opzet tests in ander project

**Review by boele — APPROVED** [review]
Ziet er goed uit.

**Pull request merged**
